# Generated by Django 2.2.4 on 2020-10-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixedAcidity', models.IntegerField(default=0)),
                ('volatileAcidity', models.IntegerField(default=0)),
                ('citricAcid', models.IntegerField(default=0)),
                ('residualSugar', models.IntegerField(default=0)),
                ('chlorides', models.IntegerField(default=0)),
                ('freeSulfurDioxide', models.IntegerField(default=0)),
                ('totalSulfurDioxide', models.IntegerField(default=0)),
                ('density', models.IntegerField(default=0)),
                ('pH', models.IntegerField(default=0)),
                ('sulphates', models.IntegerField(default=0)),
                ('alcohol', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='approvals',
        ),
    ]
