# Generated by Django 2.2.4 on 2020-10-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapp', '0002_auto_20201001_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='alcohol',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wine',
            name='chlorides',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wine',
            name='citricAcid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wine',
            name='density',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wine',
            name='fixedAcidity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wine',
            name='freeSulfurDioxide',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wine',
            name='pH',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wine',
            name='residualSugar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wine',
            name='sulphates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wine',
            name='totalSulfurDioxide',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wine',
            name='volatileAcidity',
            field=models.FloatField(default=0),
        ),
    ]
